### ISSUE TITLE
Solve the not being able to transfer error.

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-juror-front#134] opened 2018-08-23 19:41 UTC
Hi, I tried to transfer the amount provided by the interface "504041,44934273383" and got this error
![errortransfer](https://user-images.githubusercontent.com/8873352/44548026-cd478100-a714-11e8-9772-df78b6853756.png)
Removing one decimal fixes the issue.

**Comment by epiqueras** [comment] 2018-08-23 20:39
@satello API error?

**Comment by clesaege** [comment] 2018-08-24 22:30
Another user with the issue: https://youtu.be/jji4YGgN1Z4

**Comment by stefek99** [comment] 2018-08-25 11:09
While you are at it...

![image](https://user-images.githubusercontent.com/249703/44617702-95008980-a85f-11e8-99e5-88fb714dc15c.png)

Left miniscule amount and formatting is odd.

`2.9143354e-11.toFixed(18)`

**Comment by satello** [comment] 2018-08-27 22:29
It looks like the issue is when converting from a BigNumber to a float you only get 9 significant digits and by default it will round up. So if you have 1.66666... PNK it will be converted to 1.666666667. I am going to take out the conversions in the API so the front end can convert for display purposes but all passed values will be integers

**Comment by ferittuncer** [comment] 2018-08-28 06:32
Is it necessary to convert to float? Why not do calculations using big number library and when needs to be displayed convert it to string. Same way string input can be parsed to a big number.

**Comment by satello** [comment] 2018-08-28 13:52
True that would be a simpler fix for now. The front end isn't making any calculations so it can just use strings. I do think it makes sense for the API to return BigNumbers instead of strings in the future and have the front ends convert to whatever form they need

**Comment by epiqueras** [comment] 2018-08-28 14:35
Everything should stay in BN, everywhere. Only convert to strings for
rendering.

**Closed** 2018-10-02 22:19 UTC
